# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SteamPointsCalcQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import  QSize
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5.QtGui import QPalette, QBrush, QPixmap

import math 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(249, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 130, 120, 30))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 70, 120, 30))
        self.lineEdit.setStatusTip("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 249, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 250, 120, 30))
        self.lineEdit_2.setStatusTip("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 310, 120, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        MainWindow.setFixedSize(MainWindow.size()) 

        self.add_functions()




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SteamPoinsts calc"))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.label.setText(_translate("MainWindow", "Введите здесь сколько очков стим вы хотите"))
        self.label_2.setText(_translate("MainWindow", "Сколько вы потратили (ГРН)"))
        self.pushButton_2.setText(_translate("MainWindow", "Рассчитать"))

    def add_functions(self):
        self.pushButton.clicked.connect(self.butt1)
        self.pushButton_2.clicked.connect(self.butt2)



    def butt1(self):
        try:
            lineEdit_1 = self.lineEdit.text()
            res_1 = (float(lineEdit_1) / 68) * 25
            messageBox1 = QMessageBox()
            messageBox1.setWindowIcon(QIcon("SteamPoints.png"))
            messageBox1.setWindowTitle('Результат')
            res_1 = math.ceil(res_1)
            res_1 = str(res_1)
            messageBox1.setText('Вам нужно потратить ' + res_1 + ' грн')
            messageBox1.setIcon(QMessageBox.Information)
            messageBox1.setStandardButtons(QMessageBox.Ok)

            messageBox1.exec_()

        except ValueError:
            error = QMessageBox()
            error.setWindowTitle('Ошибка')
            error.setText("Вы ввели не число")
            error.setIcon(QMessageBox.Critical)
            error.setStandardButtons(QMessageBox.Ok)

            error.exec_()

        
            

    def butt2(self):
        try:
            lineEdit_2 = self.lineEdit_2.text()
            res_1 = (float(lineEdit_2) / 25) * 68
            messageBox2 = QMessageBox()
            messageBox2.setWindowIcon(QIcon("SteamPoints.png"))
            messageBox2.setWindowTitle('Результат')
            res_1 = math.ceil(res_1)
            res_1 = str(res_1)
            messageBox2.setText('Вам начислено ' + res_1 + ' очков стим')
            messageBox2.setIcon(QMessageBox.Information)
            messageBox2.setStandardButtons(QMessageBox.Ok)

            messageBox2.exec_()

        except ValueError:
            error = QMessageBox()
            error.setWindowTitle('Ошибка')
            error.setText("Вы ввели не число")
            error.setIcon(QMessageBox.Critical)
            error.setStandardButtons(QMessageBox.Ok)

            error.exec_()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    app.setStyleSheet("#MainWindow{border-image:url(C:/SteamPointsCalc/BackGraundForMyApp.png)}")
    app.setWindowIcon(QtGui.QIcon('SteamPoints.png'))
    MainWindow.show()
    sys.exit(app.exec_())
